### ISSUE TITLE
Use GitHub releases to distribute binaries?

### ISSUE THREAD

**Issue by traversaro** [ADVRHumanoids/MatLogger2#2]
The repo weights almost 10 MB, a non negligible weight for a small library. Most of this weight come from the all the history of the `.deb` packages stored in https://github.com/ADVRHumanoids/MatLogger2/tree/master/release . 
There is a specific reason for which the binary files are not added in the Release page of  GitHub ( https://github.com/ADVRHumanoids/MatLogger2/releases ) that has been specifically design to host those files ( https://help.github.com/en/articles/creating-releases ), outside of the git repo?

**Comment by alaurenzi** [comment]
Hi Silvio,
you're definitely right. I'll look into it asap

**Comment by alaurenzi** [comment]
I've (I think) successfully removed the deb files from the whole history and uploaded the latest debian on the release page. Anything else?

**Comment by traversaro** [comment]
Hi @alaurenzi , this indeed solves the issue for us, thanks a lot and sorry for the late reply.
